### ISSUE TITLE
 Invalid format, is this a valid gerber file?

### ISSUE THREAD

**Issue by danielkucera** [kirberich/gerber_to_scad#10]
Hi,
I have a gerber which fails to load. Can you please have a look?
[board.zip](https://github.com/kirberich/gerber_to_scad/files/5405176/board.zip)

**Comment by kirberich** [comment]
HI! I'm sorry for only replying to years later, but just in case you're curious, that board processes well now 
![Screenshot 2022-06-18 at 21 22 14](https://user-images.githubusercontent.com/941715/174455973-45e502b6-aad5-4a23-ab53-21b52c77ebe5.png)
