### ISSUE TITLE
Readme instructions are outdated

### ISSUE THREAD

**Issue by LordRafa** [kirberich/gerber_to_scad#12]
Hi,

I am trying to run this app standalone (without docker/service) but the instructions in the readme doesn't match current repo status.

It would be really appreciated if you could update the readme with the instructions to make this app work at the current status..

best,
rafa

**Comment by kirberich** [comment]
Hi! I think @gppk was nice enough to fix this here: https://github.com/kirberich/gerber_to_scad/pull/13

Let me know if there was something else that isn't up-to-date in the readme, but I think the instructions work
